### PR TITLE
Add toroidal magnetic field line

### PR DESCRIPTION
**Pull request by takumi-0871**
磁力線ルーチンの追加です。
rm cached gitignore という無駄なコミットがありますが、問題ないでしょうか。

### CODE REVIEW

**Comment by hirokemono** [comment]
> 磁力線ルーチンの追加です。
> rm cached gitignore という無駄なコミットがありますが、問題ないでしょうか。

Well, we'd better to make a message in English, or both in Japanese and English. 
The routines to generate zonal mean of stream function for velocity and magnetic field look fine. But, .gitignore should not be deleted. '.gitignore' file is a list of files to exclude into the repository, such as work file. For example, *.aux, .out, .toc, big, and .bbl files are temporary files for LaTeX to make the document.

**Comment by ljhwang** [comment]
I would recommend breaking up commits grouping them in multiple pull requests to make reviews and changes easier.

Best,
-Lorraine

*****************************
Lorraine Hwang, Ph.D. - Director
Computational Infrastructure for Geodynamics
UC Davis
530.752.3656
geodynamics.org

**Comment by takumi-0871** [comment]
I restored gitignore file.

**Comment by hirokemono** [comment]
This pull request should be applied to the branch Ver.2.0-alpha. Please submit pull request to  Ver.2.0-alpha again.

**Pull request closed without merging**
