### PR TITLE
Add GitHub action

### PR DESCRIPTION
**Pull request by gassmoeller**
@hirokemono: This is a conversion of the existing Jenkinsfile into using Github actions. I also added a second parallel test that uses the instructions you send me on slack to install calypso on a clean ubuntu system. I opened the PR against the Ver.1.2_update branch. I would suggest to add the new method and observe it for a few weeks before removing the existing Jenkinsfile.

### CODE REVIEW

**Comment by hirokemono** [comment]
Hi, Rene, 

I found that when we simply run 'male', make command automatically get into test.
And, in the test program fails because git actions try to run program as root, and
mpirun seems to be required a -allow-run-as-root to run asa root.

One approach is adding an option to define mpirun and options in configure, 
but I want to ask how do you treat mpirun in ASPECT.

Thanks,

Here is the part of the log.

# Test in Dynamobench_case1 directory...
make[3]: Entering directory '/__w/calypso/calypso/tests/Dynamobench_case1'
rm -f *.dat
mpirun -np 4 /__w/calypso/calypso/bin/gen_sph_grids
--------------------------------------------------------------------------
Makefile:27: recipe for target 'test' failed
mpirun has detected an attempt to run as root.
make[3]: Leaving directory '/__w/calypso/calypso/tests/Dynamobench_case1'
# Test in Dynamobench_case2 directory...
Running at root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

You can override this protection by adding the --allow-run-as-root
option to your cmd line. However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------

**Comment by gassmoeller** [comment]
Interesting, it seems the github action that I added here does not have this behavior, because it passes on my github fork. See here: https://github.com/gassmoeller/calypso/actions

However, there are also some environment variables that improve the interaction between OpenMPI and CI testers. Here are the ones we use in ASPECT:
```
# Avoid a warning
export OMPI_MCA_btl_base_warn_component_unused=0
# Prevent slowdown when oversubscribing (e.g. 4 ranks of 2 cores)
export OMPI_MCA_mpi_yield_when_idle=1
export OMPI_MCA_rmaps_base_oversubscribe=1
# Allow run as root
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
```

Do you want me to add them to the Github action as a precaution?

**Comment by hirokemono** [comment]
Hi, Rene, 
Yeah, could you add them in your fork?

And, looking at your log, I found another issue. GitHub action seems to run up to 2 MPI processes. Some of my tests need 4 MPI processes, so these tests fails with error messages. But, this situation could easily happens for users, so I update documents and configure script to set mpirun command by environment valuables after merging your update anyway.

[log.txt](https://github.com/geodynamics/calypso/files/7187996/log.txt)

And, I think to split test part from building process in Makefile, because many of computer center does not happy to run MPI programs from console.

**Comment by gassmoeller** [comment]
Hi Hiro, take a look at this new version. I added all the environment variables and now the tests run. I agree splitting the test from the make process in the future is a good idea.

However, for this change I had to remove the job that builds Calypso inside the docker container, because it runs Ubuntu 18.04. For the MPI version in Ubuntu 18.04 there is no environment variable that allows to run the test as root. The new workflow works on Ubuntu 20.04. Are you ok with that?

**Comment by hirokemono** [comment]
Hi, Rene, 

Yeah, It works! And, That is no problem to remove the test for the docker container. 

Thanks.

**Comment by gassmoeller** [comment]
Perfect, I will disable the webhook to the Jenkins server then. Feel free to delete the Jenkinsfile in the repository at at any time, it will no longer have an effect.

**Pull request merged**
